server:
  port: 8765

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: shortener-service-route
              uri: lb://shortener-service
              predicates:
                - Path=/api/shorten,/api/shorten/**,/api/urls/**

            - id: redirect-service-route
              uri: lb://redirect-service
              predicates:
                - Path=/api/redirect/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true